package jcd;

/**
 *
 * @author Shane Kennedy
 */
public enum PropertyType {
    PHOTO_ICON,
    PHOTO_TOOLTIP,
    EXPORT_JAVA_ICON,
    EXPORT_JAVA_TOOLTIP,
    
    SELECT_ICON,
    SELECT_TOOLTIP,
    RESIZE_ICON,
    RESIZE_TOOLTIP,
    ADD_CLASS_ICON,
    ADD_CLASS_TOOLTIP,
    ADD_INTERFACE_ICON,
    ADD_INTERFACE_TOOLTIP,
    REMOVE_ICON,
    REMOVE_TOOLTIP,
    UNDO_ICON,
    UNDO_TOOLTIP,
    REDO_ICON,
    REDO_TOOLTIP,
    
    ZOOM_IN_ICON,
    ZOOM_IN_TOOLTIP,
    ZOOM_OUT_ICON,
    ZOOM_OUT_TOOLTIP,
    SHOW_GRID_LABEL,
    ENABLE_SNAPPING_LABEL,
    
    NAME_LABEL,
    PACKAGE_LABEL,
    PARENT_LABEL,
    ADD_COMPONENT_ICON,
    SUBTRACT_COMPONENT_ICON,
    METHODS_LABEL,
    ADD_METHOD_TOOLTIP,
    SUBTRACT_METHOD_TOOLTIP,
    VARIABLES_LABEL,
    ADD_VARIABLE_TOOLTIP,
    SUBTRACT_VARIABLE_TOOLTIP,
    
    EXPORT_CODE_TITLE,
    EXPORT_CODE_MESSAGE,
    
    EXPORT_CODE_ERROR_TITLE,
    EXPORT_CODE_ERROR_MESSAGE,
    NAME_UPDATE_ERROR_TITLE,
    PACKAGE_UPDATE_ERROR_TITLE,
    IDENTIFIER_UPDATE_ERROR_MESSAGE
}
